const STATUS_CODE_MOVED_PERMANENTLY = 301;

const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_UNAUTHORIZED = 401;
const STATUS_CODE_FORBIDDEN = 403;
const STATUS_CODE_RESOURCE_NOT_FOUND = 404;
const STATUS_CODE_METHOD_NOT_ALLOWED = 405;
const STATUS_CODE_REQUEST_TIMEOUT = 408;
const STATUS_CODE_CONFLICT = 409;

export const STATUS_CODES = {
    // 300s
    [STATUS_CODE_MOVED_PERMANENTLY]: "Moved Permanently",
    // 400s
    [STATUS_CODE_BAD_REQUEST]: "Bad Request",
    [STATUS_CODE_UNAUTHORIZED]: "Unauthorized",
    [STATUS_CODE_FORBIDDEN]: "Forbidden",
    [STATUS_CODE_RESOURCE_NOT_FOUND]: "Not Found",
    [STATUS_CODE_METHOD_NOT_ALLOWED]: "Method Not Allowed",
    [STATUS_CODE_REQUEST_TIMEOUT]: "Request Timeout",
    [STATUS_CODE_CONFLICT]: "Conflict",
}
