---
name: CD/CI Pipeline publishing to npm registry
on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch: {}
  release:
    types:
      - published
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test project
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    name: Build and Deploy package to npm registry
    env:
      NODE_AUTH_TOKEN: ${{ secrets.PEOPLEXD_NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: https://registry.npmjs.org
      - name: Install Dependancies
        run: npm install
      - name: Build Package
        run: npm run build
      - name: Publish Package
        run: npm publish
